// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithydocument "github.com/aws/smithy-go/document"
)

type Certificate struct {

	// The certificate identifier.
	//
	// This member is required.
	CertificateId *string

	// The certificate status.
	//
	// This member is required.
	Status *string

	noSmithyDocumentSerde
}

type IdpAssociation struct {

	// The IdP identifier.
	//
	// This member is required.
	IdpId *string

	// A boolean which indicates whether the IdP is enabled.
	//
	// This member is required.
	IsEnabled bool

	// The IdP certificates.
	IdpCertificateIds []Certificate

	// The IdP OIDC association details.
	IdpOIDCAssociationValue *IdpOIDCAssociation

	// The IdP SAML association details.
	IdpSAMLAssociationValue *IdpSAMLAssociation

	// The IdP SAML configuration.
	IdpSAMLConfig *IdpSAMLConfiguration

	noSmithyDocumentSerde
}

type IdpOIDCAssociation struct {

	// The IdP OIDC configuration.
	//
	// This member is required.
	IdpOIDCConfig *IdpOIDCConfiguration

	noSmithyDocumentSerde
}

type IdpOIDCClaimDefinition struct {

	// This member is required.
	TokenClaim *string

	// This member is required.
	UserAttributeName *string

	noSmithyDocumentSerde
}

type IdpOIDCConfiguration struct {

	// This member is required.
	Audience *string

	// This member is required.
	IssuerURL *string

	// This member is required.
	UserIdentityClaimDefinition *IdpOIDCClaimDefinition

	AuthorizationEndpoint *string

	ClientId *string

	JwksUri *string

	Scopes []string

	TokenEndpoint *string

	noSmithyDocumentSerde
}

type IdpSAMLAssociation struct {

	// The IdP certificates.
	//
	// This member is required.
	IdpCertificateIds []Certificate

	// The IdP SAML configuration.
	//
	// This member is required.
	IdpSAMLConfig *IdpSAMLConfiguration

	noSmithyDocumentSerde
}

type IdpSAMLConfiguration struct {

	// This member is required.
	EntityId *string

	// This member is required.
	LoginURL *string

	WantRequestSigned bool

	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
