// Code generated by smithy-go-codegen DO NOT EDIT.

package appsauthcontrol

import (
	"context"
	"fmt"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

type validateOpListExternalIdPConfigurationsForDirectory struct {
}

func (*validateOpListExternalIdPConfigurationsForDirectory) ID() string {
	return "OperationInputValidation"
}

func (m *validateOpListExternalIdPConfigurationsForDirectory) HandleInitialize(ctx context.Context, in middleware.InitializeInput, next middleware.InitializeHandler) (
	out middleware.InitializeOutput, metadata middleware.Metadata, err error,
) {
	input, ok := in.Parameters.(*ListExternalIdPConfigurationsForDirectoryInput)
	if !ok {
		return out, metadata, fmt.Errorf("unknown input parameters type %T", in.Parameters)
	}
	if err := validateOpListExternalIdPConfigurationsForDirectoryInput(input); err != nil {
		return out, metadata, err
	}
	return next.HandleInitialize(ctx, in)
}

func addOpListExternalIdPConfigurationsForDirectoryValidationMiddleware(stack *middleware.Stack) error {
	return stack.Initialize.Add(&validateOpListExternalIdPConfigurationsForDirectory{}, middleware.After)
}

func validateOpListExternalIdPConfigurationsForDirectoryInput(v *ListExternalIdPConfigurationsForDirectoryInput) error {
	if v == nil {
		return nil
	}
	invalidParams := smithy.InvalidParamsError{Context: "ListExternalIdPConfigurationsForDirectoryInput"}
	if v.DirectoryId == nil {
		invalidParams.Add(smithy.NewErrParamRequired("DirectoryId"))
	}
	if invalidParams.Len() > 0 {
		return invalidParams
	} else {
		return nil
	}
}
