// Code generated by smithy-go-codegen DO NOT EDIT.

// Package bedrockinternal provides the API client, operations, and parameter
// types for Amazon Bedrock Internal.
//
// Describes the internal API operations for Amazon Bedrock models.
package bedrockinternal
