// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithydocument "github.com/aws/smithy-go/document"
	"time"
)

// The following types satisfy this interface:
//
//	AttributesValueMemberBooleanValue
//	AttributesValueMemberComplexListValue
//	AttributesValueMemberComplexValue
//	AttributesValueMemberStringValue
type AttributesValue interface {
	isAttributesValue()
}

type AttributesValueMemberBooleanValue struct {
	Value bool

	noSmithyDocumentSerde
}

func (*AttributesValueMemberBooleanValue) isAttributesValue() {}

type AttributesValueMemberComplexListValue struct {
	Value []map[string]AttributesValue

	noSmithyDocumentSerde
}

func (*AttributesValueMemberComplexListValue) isAttributesValue() {}

type AttributesValueMemberComplexValue struct {
	Value map[string]AttributesValue

	noSmithyDocumentSerde
}

func (*AttributesValueMemberComplexValue) isAttributesValue() {}

type AttributesValueMemberStringValue struct {
	Value string

	noSmithyDocumentSerde
}

func (*AttributesValueMemberStringValue) isAttributesValue() {}

type BearerToken struct {

	// The time of creation of the bearer token.
	CreationTime *time.Time

	// The time of expiration of the bearer token.
	ExpirationTime *time.Time

	// The bearer token.
	Token *string

	// The bearer token identifier.
	TokenId *string

	noSmithyDocumentSerde
}

// A query filter used by SearchUsers . This filter object provides the attribute
// name and attribute value to search users or groups.
type Filter struct {

	// The attribute path that is used to specify which attribute name to search.
	// Length limit is 255 characters. For example, UserName is a valid attribute path
	// for the SearchUsers API.
	//
	// This member is required.
	AttributePath *string

	// Represents the data for an attribute. Each attribute value is described as a
	// name-value pair.
	//
	// This member is required.
	AttributeValue *string

	noSmithyDocumentSerde
}

// A group object that contains the metadata and attributes for a specified group.
type Group struct {

	// The identifier for a group in the identity store.
	//
	// This member is required.
	GroupId *string

	// The display name value for the group. The length limit is 1,024 characters.
	// This value can consist of letters, accented characters, symbols, numbers,
	// punctuation, tab, new line, carriage return, space, and nonbreaking space in
	// this attribute. This value is specified at the time the group is created and
	// stored as an attribute of the group object in the identity store.
	DisplayName *string

	// Attributes of a group.
	GroupAttributes map[string]AttributesValue

	// Metadata information for a group.
	Meta *ObjectMeta

	noSmithyDocumentSerde
}

// Metadata information about an object.
type ObjectMeta struct {

	// The time when the object was created.
	CreatedAt *time.Time

	// Entity that created the object.
	CreatedBy *string

	// The time when the object was updated.
	UpdatedAt *time.Time

	// Entity that updated the object.
	UpdatedBy *string

	noSmithyDocumentSerde
}

type ProvisioningTenant struct {

	// The time when the provisioning tenant was created.
	CreationTime *time.Time

	// The provisioning tenant SCIM endpoint.
	ScimEndpoint *string

	// The provisioning tenant identifier.
	TenantId *string

	noSmithyDocumentSerde
}

// A user object that contains the metadata and attributes for a specified user.
type User struct {

	// The identifier for a user in the identity store.
	//
	// This member is required.
	UserId *string

	// A Boolean value representing whether the user is active.
	Active bool

	// Metadata information for a user.
	Meta *ObjectMeta

	// Attributes of a user.
	UserAttributes map[string]AttributesValue

	// A unique string used to identify the user. The length limit is 128 characters.
	// This value can consist of letters, accented characters, symbols, numbers, and
	// punctuation. This value is specified at the time the user is created and stored
	// as an attribute of the user object in the identity store.
	UserName *string

	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde

// UnknownUnionMember is returned when a union member is returned over the wire,
// but has an unknown tag.
type UnknownUnionMember struct {
	Tag   string
	Value []byte

	noSmithyDocumentSerde
}

func (*UnknownUnionMember) isAttributesValue() {}
