// Code generated by smithy-go-codegen DO NOT EDIT.

package types_test

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/identitystoreinternal/types"
)

func ExampleAttributesValue_outputUsage() {
	var union types.AttributesValue
	// type switches can be used to check the union value
	switch v := union.(type) {
	case *types.AttributesValueMemberBooleanValue:
		_ = v.Value // Value is bool

	case *types.AttributesValueMemberComplexListValue:
		_ = v.Value // Value is []map[string]types.AttributesValue

	case *types.AttributesValueMemberComplexValue:
		_ = v.Value // Value is map[string]types.AttributesValue

	case *types.AttributesValueMemberStringValue:
		_ = v.Value // Value is string

	case *types.UnknownUnionMember:
		fmt.Println("unknown tag:", v.Tag)

	default:
		fmt.Println("union is nil or unknown type")

	}
}

var _ []map[string]types.AttributesValue
var _ *string
var _ bool
var _ map[string]types.AttributesValue
