// Code generated by smithy-go-codegen DO NOT EDIT.

package types_test

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/identitystoreinternal/types"
)

func ExampleUserAttributesValue_outputUsage() {
	var union types.UserAttributesValue
	// type switches can be used to check the union value
	switch v := union.(type) {
	case *types.UserAttributesValueMemberBooleanValue:
		_ = v.Value // Value is bool

	case *types.UserAttributesValueMemberComplexListValue:
		_ = v.Value // Value is []map[string]types.UserAttributesValue

	case *types.UserAttributesValueMemberComplexValue:
		_ = v.Value // Value is map[string]types.UserAttributesValue

	case *types.UserAttributesValueMemberStringValue:
		_ = v.Value // Value is string

	case *types.UnknownUnionMember:
		fmt.Println("unknown tag:", v.Tag)

	default:
		fmt.Println("union is nil or unknown type")

	}
}

var _ []map[string]types.UserAttributesValue
var _ *string
var _ bool
var _ map[string]types.UserAttributesValue
