// Code generated by smithy-go-codegen DO NOT EDIT.

package types

type AuthorizationType string

// Enum values for AuthorizationType
const (
	AuthorizationTypeAuthorized    AuthorizationType = "AUTHORIZED"
	AuthorizationTypeNotAuthorized AuthorizationType = "NOT_AUTHORIZED"
)

// Values returns all known values for AuthorizationType. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (AuthorizationType) Values() []AuthorizationType {
	return []AuthorizationType{
		"AUTHORIZED",
		"NOT_AUTHORIZED",
	}
}

type AvailabilityType string

// Enum values for AvailabilityType
const (
	AvailabilityTypeAvailable    AvailabilityType = "AVAILABLE"
	AvailabilityTypeNotAvailable AvailabilityType = "NOT_AVAILABLE"
)

// Values returns all known values for AvailabilityType. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (AvailabilityType) Values() []AvailabilityType {
	return []AvailabilityType{
		"AVAILABLE",
		"NOT_AVAILABLE",
	}
}
