// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithydocument "github.com/aws/smithy-go/document"
)

type AgreementAvailability struct {

	// A string describing why the agreement availability has failed.
	ErrorMessage *string

	// Status of the agreement availability.
	Status AvailabilityType

	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
